[gyro]
template = "navx" # Type of gyro
port-type = "I2C" # One of {SPI, I2C, Serial}
port = "kMXP" # The port name as in the WPILib enum

[[modules]]
template = "team88.diff-swerve-2021.beta"
location-inches = { x = -12, y = 12 }
motors.0.can-id = 16
motors.1.can-id = 1
azimuth-sensor.can-id = 1
azimuth-sensor.pwm-id = 0

[[modules]]
template = "team88.diff-swerve-2021.beta"
location-inches = { x = -12, y = -12 }
motors.0.can-id = 2
motors.1.can-id = 3
azimuth-sensor.can-id = 1
azimuth-sensor.pwm-id = 1

[[modules]]
template = "team88.diff-swerve-2021.beta"
location-inches = { x = 12, y = -12 }
motors.0.can-id = 12
motors.1.can-id = 13
azimuth-sensor.can-id = 1
azimuth-sensor.pwm-id = 2

[[modules]]
template = "team88.diff-swerve-2021.beta"
location-inches = { x = 12, y = 12 }
motors.0.can-id = 14
motors.1.can-id = 15
azimuth-sensor.can-id = 1
azimuth-sensor.pwm-id = 3
