[gyro]
template = "navx"
port-type = "I2C"
port = "kMXP"

[[modules]]
template = "team88.diff-swerve-2021.beta"
location-inches = { x = 6.075, y = 6.075 }
motors.lo.can-id = 1
motors.hi.can-id = 16
azimuth-sensor.template = "canified-pwm"
azimuth-sensor.can-id = 1
azimuth-sensor.pwm-channel = 0
azimuth-sensor.offset = -44.17
wheel-diameter-inches = 3.45

[[modules]]
template = "team88.diff-swerve-2021.beta"
location-inches = { x = -6.075, y = 6.075 }
motors.lo.can-id = 2
motors.hi.can-id = 3
azimuth-sensor.template = "canified-pwm"
azimuth-sensor.can-id = 1
azimuth-sensor.pwm-channel = 1
azimuth-sensor.offset = -139.09
wheel-diameter-inches = 3.45

[[modules]]
template = "team88.diff-swerve-2021.beta"
location-inches = { x = -6.075, y = -6.075 }
motors.lo.can-id = 13
motors.hi.can-id = 12
azimuth-sensor.template = "canified-pwm"
azimuth-sensor.can-id = 1
azimuth-sensor.pwm-channel = 2
azimuth-sensor.offset = 125.81
wheel-diameter-inches = 3.45

[[modules]]
template = "team88.diff-swerve-2021.beta"
location-inches = { x = 6.075, y = -6.075 }
motors.lo.can-id = 14
motors.hi.can-id = 15
azimuth-sensor.template = "canified-pwm"
azimuth-sensor.can-id = 1
azimuth-sensor.pwm-channel = 3
azimuth-sensor.offset = 40.38
wheel-diameter-inches = 3.45
